CREATE TABLE CLIENT
(
  CLIENT_ID    NUMBER(6) primary key,
  CLIENT_NAME  VARCHAR2(250 BYTE),
  MOBILE       VARCHAR2(250 BYTE),
  ADDRESS      VARCHAR2(250 BYTE),
  NID          NUMBER(20)
);




Insert into CLIENT
   (CLIENT_ID, CLIENT_NAME, MOBILE, ADDRESS, NID)
 Values
   (3, 'Tarek Shawky', '0124659798', 'Cairo', NULL);
Insert into CLIENT
   (CLIENT_ID, CLIENT_NAME, MOBILE, ADDRESS, NID)
 Values
   (2, 'Marwa Hashem', '0106549878', 'Alex', NULL);
Insert into CLIENT
   (CLIENT_ID, CLIENT_NAME, MOBILE, ADDRESS, NID)
 Values
   (1, 'Ahmed Omar', '0124798987', 'Cairo', NULL);
COMMIT;




CREATE TABLE CONTRACTS
(
  CONTRACT_ID            NUMBER(6) primary key,
  CONTRACT_STARTDATE     DATE,
  CONTRACT_ENDDATE       DATE,
  CONTRACT_TOTAL_FEES    NUMBER(10),
  CONTRACT_DEPOSIT_FEES  NUMBER(10),
  CLIENT_ID              NUMBER(6),
  CONTRACT_PAYMENT_TYPE  VARCHAR2(250 BYTE),
  NOTES                  VARCHAR2(250 BYTE)
);


ALTER TABLE CONTRACTS ADD (
  CONSTRAINT FK_CLIENT 
  FOREIGN KEY (CLIENT_ID) 
  REFERENCES CLIENT (CLIENT_ID)
);



Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (101, TO_DATE('1/1/2021', 'DD/MM/YYYY'), TO_DATE('1/1/2023', 'DD/MM/YYYY'), 500000, 0, 
    1, 'ANNUAL', NULL);
Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (102, TO_DATE('1/3/2021', 'DD/MM/YYYY'), TO_DATE('1/3/2024', 'DD/MM/YYYY'), 600000, 10000, 
    2, 'QUARTER', NULL);
Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (103, TO_DATE('1/5/2021', 'DD/MM/YYYY'), TO_DATE('1/5/2023', 'DD/MM/YYYY'), 400000, 50000, 
    3, 'QUARTER', NULL);
Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (104, TO_DATE('1/3/2021', 'DD/MM/YYYY'), TO_DATE('1/3/2024', 'DD/MM/YYYY'), 700000, 0, 
    2, 'MONTHLY', NULL);
Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (105, TO_DATE('1/4/2021', 'DD/MM/YYYY'), TO_DATE('1/4/2026', 'DD/MM/YYYY'), 900000, 300000, 
    1, 'ANNUAL', NULL);
Insert into CONTRACTS
   (CONTRACT_ID, CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_TOTAL_FEES, CONTRACT_DEPOSIT_FEES, 
    CLIENT_ID, CONTRACT_PAYMENT_TYPE, NOTES)
 Values
   (106, TO_DATE('1/1/2021', 'DD/MM/YYYY'), TO_DATE('1/1/2026', 'DD/MM/YYYY'), 1000000, 200000, 
    2, 'HALF_ANNUAL', NULL);
COMMIT;




CREATE TABLE INSTALLMENTS_PAID
(
  INSTALLMENT_ID      NUMBER(6) primary key ,
  CONTRACT_ID         NUMBER(6),
  INSTALLMENT_DATE    DATE,
  INSTALLMENT_AMOUNT  NUMBER(6),
  PAID                NUMBER(6)
);



ALTER TABLE INSTALLMENTS_PAID ADD (
  CONSTRAINT FK_CONTRACT 
  FOREIGN KEY (CONTRACT_ID) 
  REFERENCES HR.CONTRACTS (CONTRACT_ID)
   );

create sequence contract_ID_seq
    start with 1
    increment by 1;
